### ISSUE TITLE
Error reading ALAMO trace for training instance with NOUTPUTS > 1 and validation dataset

### ISSUE THREAD

**Issue by sreekanthrajagopalan** [IDAES/idaes-pse#694] opened 2022-02-05 20:49 UTC
The current implementation of [alamopy.py](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py) seems to support a single validation dataset and only a single validation dataset based on the following observations:

1. `AlamoTrainer._validation_dataframe` is written to the ALM file based on hunks: [lines 630-632](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py#L630) and [lines 688-696](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py#L688).
2. No mentioned support for NVALSETS based on `supported_options' defined in [line 62](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py#L62) and no mention of NVALSETS anywhere in [alamo.py](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py). (ALAMO treats NVALSETS 1 if NVALDATA is provided per [user manual](https://minlp.com/downloads/docs/alamo%20manual.pdf).)
3. The following example code completes ALAMO execution with "Normal termination' status.

```
# alamo_error.py
import io
import pandas as pd
from idaes.surrogate.alamopy import AlamoTrainer

# training data
train_df = pd.DataFrame({
	'x1': [-5, -4, -2, 0, 1, 2, 4],
	'x2': [10, 1, 9, 2, 7, 3, 8],
	'z1': [-69, 20, -74, -3, -48, -6, -51],
	'z2': [84, -15, 85, 5, 54, 7, 55]})

# validation data
val_df = pd.DataFrame({
	'x1': [-3, -1, 3, 5],
	'x2': [4, 6, 0, 5],
	'z1': [-3, -33, 7, -4],
	'z2': [10, 40, -10, 4]})

# define labels and input bounds
input_labels = ["x1", "x2"]
output_labels = ["z1", "z2"]
bnds = {"x1": (-5, 5), "x2": (0, 10)}

# ALAMO basis
alamo_basis = {
	'linfcns': 1, 
	'constant': 1, 
	'monomialpower': [2, 3],
	'multi2power': [1],
}

# initialize SurrogateTrainer
alamo_trainer = AlamoTrainer(input_labels=input_labels,
	output_labels=output_labels, input_bounds=bnds,
	training_dataframe=train_df,
	validation_dataframe=val_df,
	**alamo_basis)

# print ALM file
stream = io.StringIO()
alamo_trainer._write_alm_to_stream(stream)
print(stream.getvalue())

# train
(alamo_trainer.status, alamo_trainer.alamo_object,
	alamo_trainer.msg) = alamo_trainer.train_surrogate()
```

However, we run into the following `RuntimeError` while reading the ALAMO trace file.
```
Traceback (most recent call last):
  File "...\alamo_error.py", line 46, in <module>
    alamo_trainer.msg) = alamo_trainer.train_surrogate()
  File "...\.venv\lib\site-packages\idaes\surrogate\alamopy.py", line 502, in train_surrogate
    trace_dict = self._read_trace_file(
  File "...\.venv\lib\site-packages\idaes\surrogate\alamopy.py", line 862, in _read_trace_file
    raise RuntimeError(
RuntimeError: Mismatch when reading ALAMO trace file. Expected OUTPUT = 1, found 2.
```

The current `AlamoTrainer._read_trace_file()` implementation assumes each line of the trace file corresponds to an output variable in the hunk: [lines 818-863](https://github.com/IDAES/idaes-pse/blob/ba1793c5f1aba9055e2cadbe151d1a3dc1631136/idaes/surrogate/alamopy.py#L818). However, ALAMO trace file includes a line for each dataset (0 for training dataset and 1, 2, ..., NVALSETS for validation datasets) for each output variable. See example below.

```
#filename, NINPUTS, NOUTPUTS, INITIALPOINTS, OUTPUT, SET, INITIALIZER, SAMPLER, MODELER, BUILDER, GREEDYBUILD, BACKSTEPPER, GREEDYBACK, REGULARIZER, SOLVEMIP, SSEOLR, SSE, RMSE, R2, ModelSize, BIC, RIC, Cp, AICc, HQC, MSE, SSEp, MADp, OLRTime, numOLRs, OLRoneCalls, OLRoneFails, OLRgsiCalls, OLRgsiFails, OLRdgelCalls, OLRdgelFails, OLRclrCalls, OLRclrFails, OLRgmsCalls, OLRgmsFails, CLRTime, numCLRs, MIPTime, NumMIPs, LassoTime, Metric1Lasso, Metric2Lasso, LassoSuccess, LassoRed, nBasInitAct, nBas, SimTime, SimData, TotData, NdataConv, OtherTime, NumIters, IterConv, TimeConv, Step0Time, Step1Time, Step2Time, TotalTime, AlamoStatus, AlamoVersion, Model
alamo_error.alm, 2, 2, 7, 1, 0, 3, 1, 1, 1, T, 0, T, 0, F, 0.347E-27, 0.347E-27, 0.704E-14, 1.00, 5, -446., 20.8, 3.00, -386., -450., 0.347E-27, 0.347E-27, 0.888E-13, 0.0000000, 247, 16, 0, 0, 0, 478, 0, 0, 0, 0, 0, 0.0000000, 0, 0.0000000, 0, 0.0000000, 0.17976931+309, 0.17976931+309, F, 0.0000000, 8, 8, 0.0000000, 0, 7, 0, 0.18750000, 1, 0, 0.0000000, 0.0000000, 0.15625000E-01, 0.0000000, 0.0000000, 0, 2021.12.28,  z1 =  - 0.99999999999999689137553 * x1 - 0.20616513343350446289142E-015 * x2 + 1.0000000000000002220446 * x1^2 - x2^2 + 0.99999999999999811262086
alamo_error.alm, 2, 2, 7, 1, 1, 3, 1, 1, 1, T, 0, T, 0, F, 0.347E-27, 0.540E-27, 0.116E-13, 1.00, 5, -443., 20.8, 3.00, -383., -446., 0.540E-27, 0.540E-27, 0.129E-13, 0.0000000, 247, 16, 0, 0, 0, 478, 0, 0, 0, 0, 0, 0.0000000, 0, 0.0000000, 0, 0.0000000, 0.17976931+309, 0.17976931+309, F, 0.0000000, 8, 8, 0.0000000, 0, 4, 0, 0.18750000, 1, 0, 0.0000000, 0.0000000, 0.15625000E-01, 0.0000000, 0.0000000, 0, 2021.12.28,  z1 =  - 0.99999999999999689137553 * x1 - 0.20616513343350446289142E-015 * x2 + 1.0000000000000002220446 * x1^2 - x2^2 + 0.99999999999999811262086
alamo_error.alm, 2, 2, 7, 2, 0, 3, 1, 1, 1, T, 0, T, 0, F, 0.247E-27, 0.247E-27, 0.594E-14, 1.00, 5, -449., 20.8, 3.00, -389., -452., 0.247E-27, 0.247E-27, 0.888E-13, 0.0000000, 247, 16, 0, 0, 0, 478, 0, 0, 0, 0, 0, 0.0000000, 0, 0.0000000, 0, 0.0000000, 0.17976931+309, 0.17976931+309, F, 0.0000000, 8, 8, 0.0000000, 0, 7, 0, 0.18750000, 1, 0, 0.0000000, 0.0000000, 0.15625000E-01, 0.0000000, 0.15625000E-01, 0, 2021.12.28,  z2 = 1.0000000000000022204460 * x2 - 1.0000000000000002220446 * x1^2 + x2^2 - 0.72986161565720566182285E-016 * x1^3 - 1.0000000000000091038288
alamo_error.alm, 2, 2, 7, 2, 1, 3, 1, 1, 1, T, 0, T, 0, F, 0.247E-27, 0.196E-27, 0.699E-14, 1.00, 5, -451., 20.8, 3.00, -390., -454., 0.196E-27, 0.196E-27, 0.107E-12, 0.0000000, 247, 16, 0, 0, 0, 478, 0, 0, 0, 0, 0, 0.0000000, 0, 0.0000000, 0, 0.0000000, 0.17976931+309, 0.17976931+309, F, 0.0000000, 8, 8, 0.0000000, 0, 538976288, 0, 0.18750000, 1, 0, 0.0000000, 0.0000000, 0.15625000E-01, 0.0000000, 0.15625000E-01, 0, 2021.12.28,  z2 = 1.0000000000000022204460 * x2 - 1.0000000000000002220446 * x1^2 + x2^2 - 0.72986161565720566182285E-016 * x1^3 - 1.0000000000000091038288
```

Also, it is not clear how the metrics are to be reported for training and validation datasets in `AlamoTrainer._results`.

**Comment by andrewlee94** [comment] 2022-02-07 14:01
@sreekanthrajagopalan The current implementation of the ALAMO interface does only support a single validation dataset. This is by design, in part due to the design of the overall IDAES surrogate modeling interface and in part due to the additional challenges associated with managing multiple dataset, some of which you touched upon in the issue above.

At this stage, we do not have the resources to extend the interface to handle multiple validation datasets. However, if you happen to have the time to try to implement the extension to the current interface, we are always open to contributions from external users.

**Comment by sreekanthrajagopalan** [comment] 2022-02-07 17:18
@andrewlee94, even with a single validation set, the interface fails when trained for multiple outputs. The only way to support validation set currently is to train each output variable using a separate trainer object.

Thanks for the looking into this issue. I will submit a PR when I get a chance to work on this.

**Comment by andrewlee94** [comment] 2022-02-07 17:34
@sreekanthrajagopalan Ah, now that part is definitely a bug that we should look into. That is hopefully a simple update to the trace file parser, although we will also need to look at how to properly validate the result (i.e. make sure we got the right line in the trace file).

**Comment by andrewlee94** [comment] 2022-02-07 17:35
Also, on the topic of metrics, we decided not to use the metrics from ALAMO itself, as the IDAES surrogates interface has its own tools for calculating metrics which give us more control over the data and greater significant figures (due to not needing to parse a text file).

**Comment by sreekanthrajagopalan** [comment] 2022-02-07 21:45
@andrewlee94 The bugfix should be straightforward - ignore rows in the trace file with SET value not equal to 0 while parsing (0 corresponds to the default/training dataset).

It makes sense to implement metrics in the SurrogateBase. I will look into it. Since _results is a technically a "private" member of AlamoTrainer, it should be an easy extension to store ALAMO metrics for all the datasets with an extra index.

**Comment by andrewlee94** [comment] 2022-02-07 21:58
So, a few comments. As I mentioned, IDAES Already has a separate `metrics` package which can calculate things like RMSE, etc., which is already fully implemented and supported. See https://github.com/IDAES/idaes-pse/blob/main/idaes/surrogate/metrics.py.

In light of this, my first reaction is to actually remove support for passing the validation set to ALAMO entirely, and just use the IDAES `metrics` package after fitting is done to calculate everything. This actually adds a lot more flexibility, as all those calculations are done in Python and can be recalculated without needing to re-run ALAMO. It also removes the need to parse more information out of the ALAMO trace file and store it in some usable fashion, and helps with debugging and maintenance (you also get metrics calculated to machine precision, rather than however many significant figures ALAMO chooses to report in the trace file). This would also be more in-line with interfaces to other tools where the fitting and validation steps are explicitly separated.

**Comment by sreekanthrajagopalan** [comment] 2022-02-07 22:32
I fully support use of surrogate/metrics for post-training pipeline tasks. However, I think we should keep the support for passing a validation set (in fact implement multiple validation sets driven by community interest) in case ALAMO can leverage these datasets for model building in the future - for e.g., use metrics based on validation set(s) for training loss function (unless of course there is going to be an API for ALAMO for these customizations). At this time, the bug is in the parsing of the trace file from what I can tell.

**Comment by andrewlee94** [comment] 2022-02-14 15:54
@sreekanthrajagopalan I just opened a PR with the fix for this issue: https://github.com/IDAES/idaes-pse/pull/710.

After talking with some ALAMO users in the team, it became apparent that the validation data is used for more than just post-fitting metrics and thus we need to support it (although the ALAMO documentation is silent on exactly how the validation data is used).

**Closed** 2022-02-18 15:46 UTC
Labels: bug, user request, Priority:High, surrogates
