### ISSUE TITLE
Installation failure on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by sodanetworks** [IDAES/idaes-pse#43] opened 2020-09-12 10:59 UTC
Hello, I followed the instructions posted on the following page: [link](https://idaes-pse.readthedocs.io/en/latest/getting_started.html#linux), as recommended in issue #42. So, I tried to do the installation based on the advanced installation guide using github [link](https://idaes-pse.readthedocs.io/en/latest/advanced_user_guide/advanced_install/index.html). Both installation methods gave the same error, which were related to psutils. They way I solved it was to manually install psutils following the instruction on page [link](https://github.com/giampaolo/psutil/blob/master/INSTALL.rst). I believe after I install psutils, it fixed the problem. Most likely the error is on the command for installation of dependencies, in particular the psutils. 

I attached my full error log during my first try. Hope that helps.

Thanks
[Installation Errors.docx](https://github.com/IDAES/idaes-pse/files/5212561/Installation.Errors.docx)

**Comment by lbianchi-lbl** [comment] 2020-10-15 23:18
Hi @sodanetworks, apologies for not getting back to you earlier, and thanks for reporting this.

The error logs you posted were useful, and seem to confirm what you mentioned re: the issue being connected to the installation of psutil. More specifically, it seems that pip ends up needing to compile psutil from source (as opposed to being able to use a "wheel", a pre-built version of the package), and then fails because it cannot find a suitable C compiler and/or headers (perhaps because they're not in a standard location, or not installed at all on the system).

Here's the relevant subset of the error logs you posted (I believe `&apos;` symbolizes single quotes in this context):

```txt
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/anaconda3/envs/IDAES1603/bin/python -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;"&apos;"&apos;/tmp/pip-install-08ea2nvs/psutil/setup.py&apos;"&apos;"&apos;; __file__=&apos;"&apos;"&apos;/tmp/pip-install-08ea2nvs/psutil/setup.py&apos;"&apos;"&apos;;f=getattr(tokenize, &apos;"&apos;"&apos;open&apos;"&apos;"&apos;, open)(__file__);code=f.read().replace(&apos;"&apos;"&apos;\r\n&apos;"&apos;"&apos;, &apos;"&apos;"&apos;\n&apos;"&apos;"&apos;);f.close();exec(compile(code, __file__, &apos;"&apos;"&apos;exec&apos;"&apos;"&apos;))&apos; bdist_wheel -d /tmp/pip-wheel-5p_tv78l
       cwd: /tmp/pip-install-08ea2nvs/psutil/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.7/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.7/psutil
  creating build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.7/psutil/tests
  running build_ext
  building &apos;psutil._psutil_linux&apos; extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/psutil
  gcc -pthread -B /home/user/anaconda3/envs/IDAES1603/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/user/anaconda3/envs/IDAES1603/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
  unable to execute &apos;gcc&apos;: No such file or directory
  C compiler or Python headers are not installed on this system. Try to run:
  sudo apt-get install gcc python3-dev
  error: command &apos;gcc&apos; failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
```

As you correctly pointed out, installing psutil via an alternative method (such as the one you used, or installing it via Conda as in #42) should be enough to solve the issue in the short term.

We're currently looking into the installation process and trying to understand if the psutil installation issues are connected and might be caused by the same underlying problem. In the meantime, I'm closing this since it appears to have been solved, but please feel free to open a new one in case you run into this or similar errors again.

**Closed by lbianchi-lbl** 2020-10-15 23:18 UTC
Labels: Priority:High
