### ISSUE TITLE
Remove Deprecated Usage of "default" Argument

### ISSUE THREAD

**Issue by bpaul4** [IDAES/idaes-pse#930] opened 2022-08-10 18:17 UTC
Following #922 , the codebase should be cleaned up wherever the old "default" argument flag is used. This is a tedious and potentially disruptive task to open pull requests given the number of files this will touch, so we should probably do this in batches.

**Comment by andrewlee94** [comment] 2022-08-10 18:22
This is a duplicate of part of #748.

**Closed by andrewlee94** 2022-08-10 18:22 UTC
