### ISSUE TITLE
IDAES Model installation issue to see vis file

### ISSUE THREAD

**Issue by sk2blue** [IDAES/idaes-pse#31] opened 2020-04-01 04:24 UTC
Hi,

I have followed all the steps in the website from IDAES to jupyterlab installtion.
Finally, I could run flowhseet_vis_demo.jpynb and generated demoflowsheet.idaes.vis file.
But, if I double click it it shows only code not the flowsheet.
Could you please advise what should I do more?
![KakaoTalk_20200401_115934343](https://user-images.githubusercontent.com/62978443/78099205-1b0d8a80-741c-11ea-887b-2177457d0e30.png)

**Comment by jghouse88** [comment] 2020-04-01 04:58
@makaylas @perrenyang can you please help @sk2blue?

**Comment by sk2blue** [comment] 2020-04-01 05:07
While I am trying re-installation, I found there is some compatibility issue. Please refer to this and advise. Thank you very much!

![capture](https://user-images.githubusercontent.com/62978443/78101287-fcaa8d80-7421-11ea-9c0e-1606f5655169.JPG)

**Comment by makaylas** [comment] 2020-04-01 16:51
Hi @sk2blue can you give me the contents of the jupyter log file that is on the second to last line in your second picture?

**Comment by sk2blue** [comment] 2020-04-02 07:47
Hi @makaylas Here is the full contents when I run 'npm install' to 'jupyter labextension link'.

![error](https://user-images.githubusercontent.com/62978443/78223273-9137ed00-7501-11ea-833a-6215e9345781.JPG)

**Comment by makaylas** [comment] 2020-04-02 16:49
@sk2blue I need the contents of `jupyterlab-debug-k8jxx9vb.log` from the second to last line of your output.

**Comment by sk2blue** [comment] 2020-04-03 00:22
@makaylas Sorry for misunderstanding. Attachment is the file you requested. Thanks!

[jupyterlab-debug-k8jxx9vb.log](https://github.com/IDAES/idaes-pse/files/4424415/jupyterlab-debug-k8jxx9vb.log)

**Comment by makaylas** [comment] 2020-04-03 17:33
@sk2blue I think the problem is that your JupyterLab version is to high. This tool was developed with JupyterLab v1. I could probably find a solution to this problem but it would take a bit of work.

Currently, we are developing a version of this tool that does not require JupyterLab at all and it should be ready in about a month. 

Would you be willing to wait for the new version or do you need a fix for the current version?

**Comment by sk2blue** [comment] 2020-04-04 12:57
@makaylas
I can wait for the new verision so please just continue to update IDAES for new version. :)
Thanks a lot!!

**Comment by ksbeattie** [comment] 2020-07-23 18:50
@sk2blue, could you try again with the new 1.6.1 release?

**Comment by ksbeattie** [comment] 2020-09-10 19:02
@sk2blue, I'm closing this assuming things are ok now.  Feel free to re-open if that's not the case.

**Closed by ksbeattie** 2020-09-10 19:02 UTC
Labels: Priority:High
