### ISSUE TITLE
Pytest fails on brand new source installation WSL2

### ISSUE THREAD

**Issue by bernalde** [IDAES/idaes-pse#236] opened 2021-03-06 00:50 UTC
Environment data
OS (Windows | Mac | Linux distro) and version: 5.4.72-microsoft-standard-WSL2 Description: Ubuntu 20.04.1 LTS Release: 20.04
Python and/or Anaconda version: Python 3.8.5 conda 4.9.2
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
idaes-pse version: idaes, version 1.9.0.dev0
pyomo version: Pyomo 6.0 (devel {master}) (CPython 3.8.5 on Linux 5.4.72-microsoft-standard-WSL2)
[idaes_test.txt](https://github.com/IDAES/idaes-pse/files/6094380/idaes_test.txt)

After doing the installation from source, and calling `idaes get-extensions`, y ran the tests via pytests. Some of them failed, see the logs below:
Full test output attached.
```
=============================================== short test summary info ================================================
FAILED idaes/commands/tests/test_commands.py::test_examples_cli_default_version - assert 0 == -1
FAILED idaes/commands/tests/test_commands.py::test_examples_install_src - FileExistsError: [Errno 17] File exists: '/...
FAILED idaes/core/tests/test_control_volume_0d.py::test_add_total_element_balances_lineraly_dependent - assert 30 == 21
FAILED idaes/core/tests/test_control_volume_1d.py::test_add_total_element_balances_lineraly_dependent - assert 30 == 21
FAILED idaes/core/util/tests/test_phase_equilibria.py::test_Txy_data_no_dew - assert [191.46973758...6254729593885] =...
FAILED idaes/generic_models/unit_models/distillation/tests/test_tray_column.py::TestBTXIdeal::test_solution - assert ...
================================ 6 failed, 3749 passed, 3 skipped in 911.96s (0:15:11) =================================
```
Each detailed test output is:
```
E       assert 0 == -1
E        +  where 0 = <Result okay>.exit_code

idaes/commands/tests/test_commands.py:131: AssertionError
```
```
>       src_dir.mkdir()

idaes/commands/tests/test_commands.py:259:
```
```
E           FileExistsError: [Errno 17] File exists: '/home/bernalde/.idaes/_scratch/examples_install_src/src'

../../../anaconda3/envs/optim/lib/python3.8/pathlib.py:1284: FileExistsError
```
```
E           assert 30 == 21
E            +  where 30 = <LogRecord: pyomo.core, 30, /home/bernalde/repos/pyomo/pyomo/common/deprecation.py, 72, "DEPRECATED: The iteritems met...ated. Use dict.items().\n(deprecated in TBD)\n(called from /home/bernalde/repos/pyomo/pyomo/core/base/component.py:838)">.levelno
E            +  and   21 = idaeslog.INFO_LOW

/home/bernalde/repos/IDAES/idaes-pse/idaes/core/tests/test_control_volume_0d.py:1846: AssertionError
```
```
E           assert 30 == 21
E            +  where 30 = <LogRecord: pyomo.core, 30, /home/bernalde/repos/pyomo/pyomo/common/deprecation.py, 72, "DEPRECATED: The iteritems met...ated. Use dict.items().\n(deprecated in TBD)\n(called from /home/bernalde/repos/pyomo/pyomo/core/base/component.py:838)">.levelno
E            +  and   21 = idaeslog.INFO_LOW

/home/bernalde/repos/IDAES/idaes-pse/idaes/core/tests/test_control_volume_1d.py:2588: AssertionError
```
```
E       assert [191.46973758...6254729593885] == [185.6468 ± 1...625 ± 1.0e-04]
E         At index 0 diff: 191.46973758055483 != 185.6468 ± 1.0e-04
E         Right contains one more item: 331.1625 ± 1.0e-04
E         Use -v to get the full diff

/home/bernalde/repos/IDAES/idaes-pse/idaes/core/util/tests/test_phase_equilibria.py:208: AssertionError
```
```
E       assert 377.28 ± 1.0e-02 == 377.2929829205527
E        +  where 377.28 ± 1.0e-02 = <function approx at 0x7f694a7c6040>(377.28, abs=0.01)
E        +    where <function approx at 0x7f694a7c6040> = pytest.approx
E        +  and   377.2929829205527 = value(<pyomo.core.base.var.SimpleVar object at 0x7f6929a2d580>)

/home/bernalde/repos/IDAES/idaes-pse/idaes/generic_models/unit_models/distillation/tests/test_tray_column.py:247: AssertionError
```

**Comment by eslickj** [comment] 2021-03-27 18:45
@jsiirola, I think so.  I put up PR #257 to help diagnose this.  It will tell us what the OS is identified as.

**Comment by eslickj** [comment] 2021-08-05 20:36
Okay, I finally ran this think on WSL2 with Ubuntu 20.04, and get-extensions worked fine.  Upon rereading the issue, it seems that the problem is likely not related to get-extensions though.  I must have been in a too much of a hurry the first time I read it.

**Comment by lbianchi-lbl** [comment] 2021-08-13 00:05
@bernalde do you know if any of these issues are still affecting you? If not, we should probably close this, as it refers to an older version of IDAES and the issues might have been addressed in the meantime.

**Comment by bernalde** [comment] 2021-08-13 14:52
They were not affecting me in the first place but I just thought it would be good to make you aware of them.
I created a new environment (same Python version) and pip installed `pyomo `followed by using main of `ideas-pse` and rerun the `pytests`. 
First, I noticed that among the dependencies `addheader `is missing (I had to `pip install` it) (see `ideas_test_2.txt`) and then I rerun the tests via pytest with some errors:
```
=========================== short test summary info ============================
FAILED idaes/generic_models/properties/core/examples/tests/test_BT_PR.py::TestBTExample::test_T_sweep
FAILED idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py::TestColumn::test_dynamic_initialization
FAILED idaes/ui/fsvis/tests/test_fsvis.py::test_visualize_save_overwrite - as...
ERROR idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py::TestColumn::test_dynamic_column_build[ProcessType.absorber]
ERROR idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py::TestColumn::test_dynamic_column[ProcessType.absorber]
= 3 failed, 4122 passed, 3 skipped, 2 xfailed, 2 errors in 1389.67s (0:23:09) ==
```
The full log is found at `ideas_test_3.txt`
[idaes_test_2.txt](https://github.com/IDAES/idaes-pse/files/6983258/idaes_test_2.txt)
[idaes_test_3.txt](https://github.com/IDAES/idaes-pse/files/6983259/idaes_test_3.txt)

**Comment by ksbeattie** [comment] 2021-11-04 18:41
@bernalde is this still happening for you?

**Comment by bernalde** [comment] 2021-12-01 22:45
I can try rerunning these again, but currently anyone with a WSL can give it a try. I can verify it later this week.

**Comment by eslickj** [comment] 2021-12-02 00:24
@bernalde, as you probably know, I don't think these failures really should affect you and IDAES should work fine.  I do have WSL and can reproduce these failures.  I can take over trying to finish resolving this, so we don't need to keep bugging you to run the tests.  I've seen very slight solver differences between platforms that can sometimes cause very delicate tests to fail occasionally.

**Comment by ksbeattie** [comment] 2022-01-13 19:57
@andrewlee94, says that the still failing test are planned on being removed.  At that point, this issue should then be closed.

**Closed** 2022-03-16 17:52 UTC
Labels: Priority:Normal
